### ISSUE TITLE
Question about the quality of the result

### ISSUE THREAD

**Issue by linpeisensh** [hlwang1124/SNE-RoadSeg#25]
Thank you for your excellent work!

I got the result as this https://github.com/hlwang1124/SNE-RoadSeg/issues/17#issuecomment-733799715.
The following is disparity, normal, prob_map
![image](https://user-images.githubusercontent.com/52672986/111180037-ee12a300-85ac-11eb-84c9-fac66eaac863.png)
![image](https://user-images.githubusercontent.com/52672986/111180054-f36fed80-85ac-11eb-9552-f33fe1deb262.png)
![image](https://user-images.githubusercontent.com/52672986/111180078-f834a180-85ac-11eb-8bc3-69864b925b8c.png)

As you can see, the final result is worse than your one in https://github.com/hlwang1124/SNE-RoadSeg/issues/17#issuecomment-733799715. 

Is the quality of my results normal?

Could you give me some advice how to improve the quality?

Thank you in advance!

**Comment by SimonSongg** [comment]
May I ask what depth camera are you using or you are using lidar?

**Comment by linpeisensh** [comment]
I don't use lidar or depth camera, I use GANet as you mentioned https://github.com/hlwang1124/SNE-RoadSeg/issues/17#issuecomment-733799715 to get the disparity with left and right images. 

I am not sure whether the prob_map is from depth or disparity ( I get the prob_map from disparity).

**Comment by hlwang1124** [comment]
Grateful if you could provide the source data to help me check the results.

**Comment by linpeisensh** [comment]
Here is the data: kitti stereo 2015, sequence 08, frame 34.
![image_2_000034](https://user-images.githubusercontent.com/52672986/111270320-011a8700-8630-11eb-80ef-3c3d72e83379.png)
![image_3_000034](https://user-images.githubusercontent.com/52672986/111270324-024bb400-8630-11eb-91a3-c1d05805d9a7.png)

I want to know:
```depth_image = cv.imread('xxx.png', cv.IMREAD_ANYDEPTH) ```(line 30 in run_example.py) Here, is xxx.png disparity or depth?

**Comment by hlwang1124** [comment]
Hi, @linpeisensh . For your question, xxx.png means depth.

Since the pre-trained weight is obtained given as input depth images, it is better to first transform disparity images to depth images. I have tested your data. The disparity image is generated by GANet. I also revise the code in `run_example.py` as follows:
```
depth_image = cv2.imread(os.path.join('examples', 'depth_u16.png'), cv2.IMREAD_ANYDEPTH)
depth_image = depth_image.astype(np.float32)
row= depth_image.shape[0]
col= depth_image.shape[1]
depth_image= np.true_divide(np.ones((row,col)), depth_image)
depth_image= depth_image * 721.5377* 0.537 * 256.0
```
The results seem acceptable.
Disparity image:
![depth_u16](https://user-images.githubusercontent.com/25403947/111298333-97c76200-8689-11eb-9503-e515070f033f.png)
Normal image:
![normal](https://user-images.githubusercontent.com/25403947/111298372-a31a8d80-8689-11eb-9ef9-beee02347d0c.png)
Probability map:
![prob_map](https://user-images.githubusercontent.com/25403947/111298408-ac0b5f00-8689-11eb-9c89-055a74d8c18f.png)

**Comment by linpeisensh** [comment]
Thank you for your answer, it works!

**Comment by linpeisensh** [comment]
Another question:
Why is the road segmentation only in the bottom half of the picture? Could we get the road segmentation in the upper part of the picture?

**Comment by hlwang1124** [comment]
That is because the road area generally locates in the bottom half of the picture. If the road area locates in the upper part, the network should be able to handle it. One possible revision is to comment out Line 22-23 in `models/sne_model.py`. This revision can enable the model to generate the surface normal in the upper part, which may be very important for corresponding road segmentation in the upper part.

**Comment by linpeisensh** [comment]
Thank you for your answer!
