### ISSUE TITLE
Can this model segment road without depth information?

### ISSUE THREAD

**Issue by hmf17** [hlwang1124/SNE-RoadSeg#26]
I am wondering  if this model can deal with the segmentation task without the depth image or by changing some components to achieve this.

**Comment by hlwang1124** [comment]
Hi, @hmf17 . Please refer to this issue #23 .

**Comment by hmf17** [comment]
> Hi, @hmf17 . Please refer to this issue #23 .

Thanks for your suggestions and it helps me a lot!
Very appreciate!

**Comment by hmf17** [comment]
> Hi, @hmf17 . Please refer to this issue #23 .

Hi, hlwang1124
I have used monodepth2([link](https://github.com/nianticlabs/monodepth2)) to generate depth image and combined it with this SNE-RoadSeg model, but it doesn't seem to predict well for the segmentation result.
I've also noticed that your depth image with type of uint16 which is different from other kinds of depth image. What should we do if we want to use other depth image generating by other networks?

**Comment by hlwang1124** [comment]
Hi, @hmf17 . The depth images we used are computed by `uint16(distance * 1000)`, where the unit of the distance is meter. The distance on the KITTI dataset is obtained based on the LiDAR data.

Considering that you are using monocular depth estimation approaches to obtain depth images, I suggest you first check the normal images. If the normal estimation is acceptable but the segmentation results are still not good, I think that's because the deployed domain has much difference from the KITTI dataset. Under such circumstance, I suggest you re-train the network using the data in the deployed domain.

**Comment by hmf17** [comment]
Hi, @hlwang1124 
It is very grateful that you can reply my question and your suggestions are really valuable.
I will follow your advice and try to solve this problems.
Very appreciate!
