### ISSUE TITLE
Test result is nan

### ISSUE THREAD

**Issue by zeng32** [hlwang1124/SNE-RoadSeg#4]
Thanks again for your previous reply!

After the env been set up(datasets, pretrained model), I run the test script:
`bash ./scripts/test.sh`
the F_score is nan as shown below:

```
model [RoadSegModel] was created
loading the model from ./checkpoints/kitti/kitti_net_RoadSeg.pth
---------- Networks initialized -------------
[Network RoadSeg] Total number of parameters : 201.325 M
-----------------------------------------------
Epoch kitti test loss: 0.838 loss: 0.569 
Epoch kitti glob acc : 0.821, pre : 0.000, recall : nan, F_score : nan, IoU : 0.000
```
No error occurred,
Would you please enlighten me on which part probably went wrong?

Thanks in advance!

**Comment by hlwang1124** [comment]
Hi, zeng32. Sorry for the inconvenience.

If you directly run the test script, you will get the KITTI test results. Note that we do not have the ground truth labels for the KITTI testing set, so we simply use background masks (all 0) as ground truth labels, which leads to the circumstance that you met. We do this because we do not want to destroy the consistency of the code.

If you want to know the performance on the KITTI test results, the only way is to submit the results on the KITTI server. If you want to test the performance on your own testing set that has the ground truth labels, you can first put your testing dataset in `datasets/testing`, then delete `--no_label` in `test.sh`, and run `test.sh`. We use `--no_label` to indicate whether we have the ground truth labels for the testing set.

**Comment by zeng32** [comment]
Thanks very much for the detailed explanation!
Sorry for the late response, because I was trying to use your R2D dataset as testing dataset with labels.
As the R2D dataset you provided has a different naming convention, After I adapt the R2D dataset to the same naming convention:
-datasets:
--|kitti
----|testing:
------|calib
------|depth_u16
------|image_2 
I got the following error:
```
model [RoadSegModel] was created
loading the model from ./checkpoints/kitti/kitti_net_RoadSeg.pth
---------- Networks initialized -------------
[Network RoadSeg] Total number of parameters : 201.325 M
-----------------------------------------------
len::: 0
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    avg_test_loss = torch.mean(torch.stack(test_loss_iter))
RuntimeError: stack expects a non-empty TensorList
``
```
It seems like the dataloader can not recognize the new R2D dataset, is it right?

**Comment by hlwang1124** [comment]
Yes. Since the data format of our R2D dataset is different from it of the KITTI dataset, you need to write a new dataloader.

**Comment by zeng32** [comment]
Thanks for your explanation!
Quick question:
Do you have recommendations for the parameters configuration? eg,, batch_size, learning_rate...

**Comment by hlwang1124** [comment]
The hyperparameters that I adopt are shown in `options`. You can adjust them according to the performance.

**Comment by zeng32** [comment]
So, the default settings in the code.
Thanks very much for your kind help!

**Comment by zeng32** [comment]
Sorry to append on this issue.

After training with the default hyperparameters, my evaluation result from kitti server is not as good as in your report:
                       MaxF
UM_Road:     95.12%
UMM_Road: 97.05%
UU_Road :    94.39%
urban_road:  95.76%

Do you mind give me any suggestions to improve the performance?
Thanks in advance.
