### ISSUE TITLE
R2D dataset download problem

### ISSUE THREAD

**Issue by Kaimingfan** [hlwang1124/SNE-RoadSeg#6]
I can not  download this dataset,

Downloads are frequently interrupted！

**Comment by hlwang1124** [comment]
Thanks for your feedback. The R2D dataset has been uploaded to a new network disc. I hope you can download it from http://gofile.me/4jm56/N5PLZWFUT successfully.

**Comment by Kaimingfan** [comment]
I am sorry ,when I use wget command download this dataset, It can not download successfully.
Could you give me a url which wget command can download successfully.

**Comment by hlwang1124** [comment]
It's no problem. However, I'm sorry that I'm busy with other things. I will try to update the link ASAP, maybe this weekend.

**Comment by Kaimingfan** [comment]
Thank u very much.

**Comment by hlwang1124** [comment]
Hi, Kaiming. I have submitted the dataset to Baidu Netdisk. Due to the size limitation, I split the whole dataset into two sets, [R2D_1.zip](https://pan.baidu.com/s/1w9Rm7uoBgfYrbORavZ9wXQ) with the extraction code x307 and [R2D_2.zip](https://pan.baidu.com/s/17vtfh8KDLnxjMMhFZIJubQ) with the extraction code rz2m. Hope you can download them successfully.

**Comment by Kaimingfan** [comment]
Thanks for your great work and kindly reply.
