### ISSUE TITLE
How to generate images of depth_u16.png type

### ISSUE THREAD

**Issue by liuyuxun12** [hlwang1124/SNE-RoadSeg#8]
hi, I have some well-labeled 0\1 tags and related training images. I want to know how to generate images of the depth_u16.png type required for training

**Comment by hlwang1124** [comment]
We use sparse LiDAR points to generate dense depth images. Some details are mentioned at #7. The data format of the depth_u16.png is: depth_u16 = 1000 * real_depth (in meters).

If you only have color images, one way to obtain dense depth images is to adopt existing monocular depth estimation networks. However, the performance of freespace detection may degrade since the depth images generated by monocular depth estimation networks are not as accurate as those generated from sparse LiDAR points.

**Comment by mei123hao** [comment]
Hello Wang, I try to generate dense depth images from lidar data too. But the generated depth image result seems different from your provided depth_u16. It also influences the inference performance. Can you provide your dense depth images generation code for us? Thanks a lot! @hlwang1124
